name: cupcake_core
description: Core shared types and logic for Cupcake app
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  lints: ^3.0.0
